name = "karpov-portfolio"
compatibility_date = "2024-01-01"

[build]
command = "npm run build"
cwd = "."
watch_dir = "app"

[build.upload]
format = "modules"

[[build.upload.rules]]
type = "ESModule"
globs = ["**/*.js"]

[build.environment_variables]
NODE_VERSION = "20"

# Cloudflare Pages specific settings for static export
pages_build_output_dir = "out"

# Enable modern JS features
[build.modern]
enabled = true

[vars]
NODE_ENV = "production"

[env.production.vars]
NODE_ENV = "production"

[env.preview.vars]
NODE_ENV = "preview"