name = "karpov-portfolio"
compatibility_date = "2024-01-01"

[build]
command = "npm run build"
cwd = "."
watch_dir = "app"

[build.upload]
format = "modules"

[[build.upload.rules]]
type = "ESModule"
globs = ["**/*.js"]

[build.environment_variables]
NODE_VERSION = "22.16.0"
NPM_FLAGS = "--production=false"

# Cloudflare Pages specific settings for static export
pages_build_output_dir = "out"

# Enable modern JS features and optimizations
[build.modern]
enabled = true

# Enhanced caching for faster builds
[build.cache_rules]
enabled = true

[vars]
NODE_ENV = "production"

[env.production.vars]
NODE_ENV = "production"

[env.preview.vars]
NODE_ENV = "preview"

# Headers for security and performance
[[headers]]
for = "/*"
[headers.values]
X-Frame-Options = "DENY"
X-Content-Type-Options = "nosniff"
Referrer-Policy = "strict-origin-when-cross-origin"
Permissions-Policy = "camera=(), microphone=(), geolocation=()"

[[headers]]
for = "/_next/static/*"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

# Redirect rules for better SPA support
[[redirects]]
from = "/*"
to = "/index.html"
status = 200