import { Project } from '@/types'

export const PROJECTS: Project[] = [
  {
    id: '1',
    title: 'BMAD Multi-Agent System',
    description: 'A sophisticated multi-agent system for automated development workflows, featuring AI-powered code generation, testing, and deployment orchestration.',
    technologies: ['TypeScript', 'React', 'Node.js', 'Python', 'AI/ML', 'Docker'],
    images: ['/images/projects/bmad-1.jpg', '/images/projects/bmad-2.jpg'],
    demoUrl: 'https://bmad.dev',
    githubUrl: 'https://github.com/karpovpw/bmad',
    featured: true,
    category: 'web',
  },
  {
    id: '2',
    title: 'DeFi Yield Optimizer',
    description: 'Smart contract-based decentralized finance protocol that automatically optimizes yield farming strategies across multiple liquidity pools.',
    technologies: ['Solidity', 'Web3.js', 'React', 'Hardhat', 'Chainlink'],
    images: ['/images/projects/defi-1.jpg', '/images/projects/defi-2.jpg'],
    demoUrl: 'https://defi-optimizer.dev',
    githubUrl: 'https://github.com/karpovpw/defi-optimizer',
    featured: true,
    category: 'crypto',
  },
  {
    id: '3',
    title: 'AI-Powered Portfolio Analyzer',
    description: 'Machine learning application that analyzes investment portfolios and provides personalized recommendations using advanced algorithms.',
    technologies: ['Python', 'TensorFlow', 'React', 'FastAPI', 'PostgreSQL'],
    images: ['/images/projects/portfolio-ai-1.jpg'],
    demoUrl: 'https://portfolio-ai.dev',
    githubUrl: 'https://github.com/karpovpw/portfolio-ai',
    featured: false,
    category: 'web',
  },
  {
    id: '4',
    title: 'NFT Marketplace',
    description: 'Full-featured NFT marketplace with auction functionality, creator royalties, and multi-chain support.',
    technologies: ['Next.js', 'Ethers.js', 'IPFS', 'Polygon', 'OpenSea SDK'],
    images: ['/images/projects/nft-market-1.jpg', '/images/projects/nft-market-2.jpg'],
    demoUrl: 'https://nft-market.dev',
    githubUrl: 'https://github.com/karpovpw/nft-marketplace',
    featured: true,
    category: 'crypto',
  },
  {
    id: '5',
    title: 'Real-time Collaboration Platform',
    description: 'WebRTC-based real-time collaboration tool with video conferencing, screen sharing, and document editing capabilities.',
    technologies: ['WebRTC', 'Socket.io', 'React', 'Node.js', 'MongoDB'],
    images: ['/images/projects/collab-1.jpg'],
    demoUrl: 'https://collab-platform.dev',
    githubUrl: 'https://github.com/karpovpw/collab-platform',
    featured: false,
    category: 'web',
  },
  {
    id: '6',
    title: 'Smart Contract Security Auditor',
    description: 'Automated security auditing tool for smart contracts using static analysis and formal verification techniques.',
    technologies: ['Solidity', 'Python', 'Slither', 'Mythril', 'Hardhat'],
    images: ['/images/projects/security-1.jpg'],
    demoUrl: 'https://security-auditor.dev',
    githubUrl: 'https://github.com/karpovpw/security-auditor',
    featured: false,
    category: 'crypto',
  },
  {
    id: '7',
    title: 'E-commerce Analytics Dashboard',
    description: 'Comprehensive analytics dashboard for e-commerce platforms with real-time metrics, customer behavior analysis, and predictive insights.',
    technologies: ['React', 'D3.js', 'Node.js', 'Redis', 'PostgreSQL'],
    images: ['/images/projects/ecommerce-1.jpg', '/images/projects/ecommerce-2.jpg'],
    demoUrl: 'https://ecommerce-dashboard.dev',
    githubUrl: 'https://github.com/karpovpw/ecommerce-dashboard',
    featured: false,
    category: 'web',
  },
  {
    id: '8',
    title: 'Blockchain Bridge Protocol',
    description: 'Cross-chain bridge protocol enabling seamless asset transfers between different blockchain networks with minimal fees.',
    technologies: ['Solidity', 'Rust', 'Web3.js', 'Polkadot', 'Cosmos SDK'],
    images: ['/images/projects/bridge-1.jpg'],
    demoUrl: 'https://bridge-protocol.dev',
    githubUrl: 'https://github.com/karpovpw/bridge-protocol',
    featured: true,
    category: 'crypto',
  },
]

export const PROJECT_CATEGORIES = [
  { value: 'all', label: 'All Projects' },
  { value: 'web', label: 'Web Development' },
  { value: 'crypto', label: 'Blockchain & Crypto' },
  { value: 'mobile', label: 'Mobile Apps' },
  { value: 'other', label: 'Other' },
]

export const PROJECT_TECHNOLOGIES = [
  'React', 'Next.js', 'TypeScript', 'Node.js', 'Python', 'Solidity',
  'Web3.js', 'Ethers.js', 'Docker', 'Kubernetes', 'AWS', 'PostgreSQL',
  'MongoDB', 'Redis', 'GraphQL', 'TensorFlow', 'PyTorch', 'AI/ML',
  'Hardhat', 'Chainlink', 'IPFS', 'WebRTC', 'Socket.io', 'D3.js',
  'Rust', 'Polkadot', 'Cosmos SDK', 'Slither', 'Mythril', 'FastAPI',
]